"""empty message

Revision ID: c889319bf828
Revises: 4a0709d8f017
Create Date: 2025-05-19 21:53:20.245407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c889319bf828'
down_revision = '4a0709d8f017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_column('token')

    # ### end Alembic commands ###
