import weaviate
from langchain_core.vectorstores import VectorStoreRetriever
from langchain_community.embeddings import QianfanEmbeddingsEndpoint
from langchain_weaviate import WeaviateVectorStore
import weaviate.connect
